apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-cert
  namespace: unifi-ns
spec:
  dnsNames:
    - unifi.hlads.net
  secretName: unifi-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer