apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-home-cert
  namespace: default
spec:
  dnsNames:
    - unifi.home.hlads.net
  secretName: unifi-home-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer