apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi-ingress
  namespace: unifi-ns
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
  - hosts:
    - unifi.hlads.net
    secretName: unifi-tls
  rules:
  - host: unifi.hlads.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unifi-service
            port:
              number: 443
