apiVersion: v1
kind: Service
metadata:
  name: unifi-service
spec:
  selector:
    app: unifi
  ports:
    - protocol: TCP
      name: https
      port: 443 # Default port for image
      targetPort: 8443