apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: unifi-home-set
spec:
  selector:
    matchLabels:
      app: unifi-home
  replicas: 1
  template:
    metadata:
      labels:
        app: unifi-home
    spec:
      containers:
      - name: unifi-home
        image: jacobalberty/unifi
        ports:
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 8443
        - protocol: TCP
          port: 8843
        - protocol: TCP
          port: 8880
        - protocol: UDP
          port: 3478
        - protocol: TCP
          port: 6789
  volumeClaimTemplates:
  - metadata:
      name: unifi-home-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: do-block-storage