apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: unifi-home-set
spec:
  selector:
    matchLabels:
      app: unifi-home
  serviceName: "unifi-home-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
      - name: unifi-home
        image: jacobalberty/unifi
        args:
        - sleep
        - infinity
        volumeMounts:
        - mountPath: "/unifi"
          name: unifi-home-pvc
  volumeClaimTemplates:
  - metadata:
      name: unifi-home-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: do-block-storage